name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup AWS credential
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.key-id}}
          aws-secret-access-key: ${{secrets.access-key}}
          aws-region: ap-southeast-1
      - name: Setup Java JDK
        uses: actions/setup-java@v3.12.0
        with:
          java-version: ${{inputs.java-version}}
      - name: Retreive AWS CodeArtifact Token    
        run: | 
              export CODEARTIFACT_URL=`aws codeartifact get-repository-endpoint --domain ${{secrets.ARTIFACT_DOMAIN}} --repository ${{secrets.ARTIFACT_REPO}} --format maven --output text`
              export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain ${{secrets.ARTIFACT_DOMAIN}} --query authorizationToken --output text`
      - name: Create Maven setting.xml
        uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: '[{"id": "codeartifact", "username": "aws", "password": "${env.CODEARTIFACT_AUTH_TOKEN}"}]'
      - name: Build 
        run: mvn compile
      - name: Publish artifact
        run: |
             mvn deploy:deploy-file -DgroupId=com.test.abc \
              -Dversion=${{github.sha}} \
              -Dpackaging=jar \
              -Dfile=app.jar \
              -DrepositoryId=codeartifact \
              -Durl=${env.CODEARTIFACT_URL}
